spring.jpa.hibernate.ddl-auto=update

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:demo_bank_v1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Dialect
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.address=127.0.0.1
server.port=8070

# Disable Default Error Page
server.error.whitelabel.enabled=false

demoBank.app.secret=helloDarknessMyOldFriendIComeToTalkWithYouAgain
demoBank.app.expires.in=604800